version: '3.8'

services:
  face-aging-api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
      - ./results:/app/results
    environment:
      - FLASK_ENV=production
      - MODEL_PATH=/app/models/face_aging_model.pth
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - face-aging-api
    restart: unless-stopped
